project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - quarto/**
    
    
author:
  - name: Hannah Rosenthal
    affiliations:
      - Albert Einstein College of Medicine
    email: hannah.rosenthal@einsteinmed.edu
  - name: Vagish Hemmige
    affiliations:
      - Montefiore Medical Center/ Albert Einstein College of Medicine
    email: vahemmig@montefiore.org



website:
  site-url: https://vagishhemmige.github.io/HIV-SLK-outcomes
  repo-url: https://github.com/VagishHemmige/HIV-SLK-outcomes
  repo-actions: [edit, issue]
  title: "HIV SLK Outcomes"

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home  

      
      - section: Setup and helper functions
        contents:
          - href: quarto/setup.qmd
            text: Setup
          - href: quarto/functions.qmd
            text: Functions

      - section: Code to create tables and figures
        contents:
          - href: quarto/tables.qmd
            text: Tables
          - href: quarto/figures.qmd
            text: Figures


custom-callout:
  Rcode:
    icon: true
    icon-symbol: "ðŸ’» "
    color: "pink"

filters:
- custom-callout

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
    code-summary: "Click to show/hide R Code"

